version: mlr_hybrid_{build}
image: Visual Studio 2019
configuration: Release
platform: Win32
shallow_clone: true
environment:
  DXSDK: '%DXSDK_DIR%'
before_build:
- cmd: >-
    echo %PLATFORM%

    echo %CONFIGURATION%

    echo mlr_hybrid_%APPVEYOR_REPO_TAG_NAME%_%PLATFORM%.7z
build:
  project: ./engine.sln
  verbosity: minimal
after_build:
- cmd: >-
    set COR_PLAT=%PLATFORM%

    IF "%COR_PLAT%" == "Win32" set COR_PLAT=x86

    set APPVEYOR_VERSION=%APPVEYOR_BUILD_VERSION%_%COR_PLAT%

    echo %APPVEYOR_VERSION%
    
    md dist

    echo ===================== engine files =====================

    md dist\engine

    copy opt\start_%COR_PLAT%.bat dist\engine

    md dist\engine\bin_%COR_PLAT%

    copy intermediate\%PLATFORM%-%CONFIGURATION%\*.exe dist\engine\bin_%COR_PLAT%\

    copy intermediate\%PLATFORM%-%CONFIGURATION%\*.dll dist\engine\bin_%COR_PLAT%\

    echo appveyor PushArtifact mlr_hybrid_%APPVEYOR_REPO_TAG_NAME%_%COR_PLAT%.7z release

    cd dist\engine

    7z a ..\..\mlr_hybrid_%APPVEYOR_REPO_TAG_NAME%_%COR_PLAT%.7z

    cd ..\..

    echo appveyor PushArtifact mlr_hybrid_%APPVEYOR_REPO_TAG_NAME%_%COR_PLAT%.7z release

    copy mlr_hybrid_%APPVEYOR_REPO_TAG_NAME%_%COR_PLAT%.7z mlr_hybrid_%APPVEYOR_VERSION%.7z

    appveyor PushArtifact mlr_hybrid_%APPVEYOR_VERSION%.7z
artifacts:
- path: .\mlr_hybrid_$(appveyor_repo_tag_name)_$(cor_plat).7z
  name: release
